# Generated by Django 4.0.3 on 2022-09-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0002_usertypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='fdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filerequest',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeapp.station'),
        ),
    ]
