# Generated by Django 4.0.3 on 2022-09-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0003_filerequest_fdate_alter_filerequest_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='height',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='thumb',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='criminal',
            name='weight',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='optype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='firdate',
            field=models.DateField(auto_now=True),
        ),
    ]
