# Generated by Django 4.0.3 on 2022-09-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0004_criminal_age_criminal_gender_criminal_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedlist',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
