# Generated by Django 4.0.3 on 2022-09-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0005_wantedlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedlist',
            name='wdate',
            field=models.DateField(auto_now=True),
        ),
    ]
