# Generated by Django 4.0.3 on 2022-09-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0007_alter_complaint_cdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingitems',
            name='contact',
        ),
    ]
