# Generated by Django 4.0.3 on 2022-09-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0008_remove_missingitems_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
