# Generated by Django 4.0.3 on 2022-09-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0009_missingperson_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='status',
            field=models.CharField(default='registered', max_length=100, null=True),
        ),
    ]
