# Generated by Django 4.0.3 on 2022-09-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0010_missingperson_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='cdate',
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='udate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='missingpersonupdate',
            name='udate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='missingthingsupdate',
            name='udate',
            field=models.DateField(auto_now=True),
        ),
    ]
