# Generated by Django 4.0.3 on 2022-10-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0011_remove_fir_cdate_alter_complaintupdate_udate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersonupdate',
            name='stname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
