# Generated by Django 4.0.3 on 2022-11-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0013_publicuser_aid_publicuser_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
